defaults:
  db:
    location: mongo
    name: army_ant
    type: mongo
  eval:
    metrics:
      favorite:
        - GMAP
        - MAP
        - NDCG@10
        - P@10
    location: /home/army-ant/data/eval
  service:
    ner:
      entity_list: /opt/army-ant/gazetteers/all.txt
  depend:
    stanford-ner: /opt/stanford-ner-2015-12-09
  jvm:
    memory: 5120
    other_args: -XX:+UseConcMarkSweepGC

engines:
  lucene-inex-3t-nl:
    name: INEX 3T-NL - Lucene
    db:
      name: inex
    index:
      type: lucene
      location: /home/army-ant/data/indexes/inex-3t-nl/lucene
    ranking:
      default:
        id: tf_idf
      functions:
        tf_idf:
          name: TF-IDF
        bm25:
          name: BM25
          params:
            k1: [1.2, 1, 1.8]
            b: [0.75, 0.5, 1]
        dfr:
          name: DFR
          params:
            BM: [BE, G, P, D, In, Ine, IF]
            AE: [L, B, Disabled]
            N: [H1, H2, H3, Z, Disabled]

  hgoe-inex-3t-nl:
    name: INEX 3T-NL - Hypergraph-of-Entity
    db:
      name: inex
    index:
      type: hgoe
      location: /home/army-ant/data/indexes/inex-3t-nl/hgoe
      preload: true
    ranking:
      default:
        id: random_walk
        params:
          l: 2
          r: 10
      functions:
        random_walk:
          name: Random Walk Score
          params:
            l: [1, 2, 3, 4, 5, 6]
            r: [10, 25, 50, 100, 1000, 10000]
