defaults:
  db:
    location: mongo
    name: army_ant
    type: mongo
  eval:
    metrics:
      favorite:
        - GMAP
        - MAP
        - NDCG@10
        - P@10
    location: /home/army-ant/data/eval
  service:
    ner:
      entity_list: /opt/army-ant/gazetteers/all.txt
  depend:
    stanford-ner: /opt/stanford-ner-2015-12-09
  jvm:
    memory: 5120
    other_args: -XX:+UseConcMarkSweepGC

engines:
  lucene-inex-3t-nl:
    name: INEX 3T-NL - Lucene
    db:
      name: aa_inex
    index:
      type: lucene
      location: /home/army-ant/data/indexes/inex-3t-nl/lucene
    ranking:
      default:
        id: tf_idf
      functions:
        tf_idf:
          name: TF-IDF
        bm25:
          name: BM25
          params:
            k1: [1.2, 1, 1.8]
            b: [0.75, 0.5, 1]
        dfr:
          name: DFR
          params:
            BM: [BE, G, P, D, In, Ine, IF]
            AE: [L, B, Disabled]
            N: [H1, H2, H3, Z, Disabled]

  hgoe-inex-3t-nl:
    name: INEX 3T-NL - Hypergraph-of-Entity
    db:
      name: aa_inex
    index:
      type: hgoe
      location: /home/army-ant/data/indexes/inex-3t-nl/hgoe
      preload: true
    ranking:
      default:
        id: random_walk
        params:
          l: 2
          r: 100
          nf: 0
          ef: 0
          d: 0.15
          n: 100000
          norm: false
          expansion: true
          directed: true
          weighted: false
      functions:
        random_walk:
          name: Random Walk Score
          params:
            l: [1, 2, 3, 4, 5, 6]
            r: [10, 100, 250, 500, 750, 1000, 2500, 5000, 10000]
            nf: [0, 10, 100, 500, 1000]
            ef: [0, 10, 100, 500, 1000]
            expansion: [true, false]
            directed: [true, false]
            weighted: [true, false]
        hyperrank:
          name: HyperRank
          params:
            d: [0, 0.15, 0.25, 0.5, 0.75, 0.85, 1]
            n: [1000, 10000, 100000, 1000000]
            expansion: [true, false]
            weighted: [true, false]
            norm: [true, false]
