version: '3'

services:
  mongo:
    image: mongo
    networks:
      - army_ant

  mongo-data:
    build: ./mongo-data
    depends_on:
      - mongo
    networks:
      - army_ant
  
  army-ant:
    image: jldevezas/army-ant:latest
    ports:
      - "8080:8080"
    volumes:
      - ./data:/home/army-ant/data
    depends_on:
      - mongo
    networks:
      - army_ant

networks:
  army_ant: {}
